config/routes.rb
Rails.application.routes.draw do

  get 'events/:id/dashboard', to: 'events#dashboard', id: /\d+/, as: 'event_dashboard'
  get 'events/:id/pledge-breakdown', to: 'events#pledge_breakdown', id: /\d+/, as: 'event_pledge_breakdown'
  resources :events do
    resources :pledges, only: [:new]
    resources :teams, only: [:new]
  end
  resources :teams, except: [:index] do
    resources :pledges, only: [:new]
  end
  resources :pledges, only: [:create]
  get 'pledges/process_pending', to: 'pledges#process_pending', as: 'process_pending_pledge'

  resources :users, only: [:new, :create]

  devise_for :users, :controllers => {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }, :skip => [:passwords]

  devise_scope :user do

    get "/users/password/reset/new" => "users/password_resets#new"
    post "/users/password/reset" => "users/password_resets#create"
    get "/users/password/reset/edit" => "users/password_resets#edit"
    put "/users/password/reset" => "users/password_resets#update"
  end

  get 'tour' => 'home#tour'
  get 'about' => 'home#about'

  root 'home#index'

  get ':event_url_key' => 'events#show', as: 'show_event', constraints: ReservedUrlKeyConstraint.new

end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  belongs_to :team
  belongs_to :donor, :class_name => 'User'
  has_one :event, :through => :team

  validates :amount, :team, :donor, :presence => true
  validates :anonymous, :monthly, :inclusion => {:in => [true, false]}
  validates :amount, numericality: { greater_than: 0 }
  validates :comment, length: { maximum: 255 }
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController

  def new
    team_id = params[:team_id]
    unless team_id && (team = Team.find_by_id(team_id))
      team_id = nil
      event_id = params[:event_id]
      unless event_id && (@event = Event.find_by_id(event_id))
        flash[:alert] = "Please select the event for which you'd like to submit a new pledge."
        return
      end
    end

    @pledge = Pledge.new(team_id: team_id)
  end

  def create
    team_id = pledge_params[:team_id]
    return if !is_valid_team?(team_id)

    team = Team.find_by_id(team_id)
    if team.event.has_ended?
      flash[:alert] = 'The event has ended. Please contact the coordinator directly to submit any further pledges/or donations.'
      redirect_to team.event
      return
    end

    create_pledge(pledge_params)
    return
  end

  def process_pending
    if session[:pending_pledge].blank?
      flash[:alert] = 'Unable to process pledge. Please try again. Thanks!'
      redirect_to :back
      return
    end

    create_pledge(session[:pending_pledge])
  end

private

  def create_pledge(pledge_attrs)
    session[:pending_pledge] = nil

    @pledge = Pledge.new(pledge_attrs)
    @pledge.donor = current_user if current_user

    # Allow pledges to be submitted without logging in, but require an account to be created
    # after pledge details are entered.
    if !@pledge.donor
      session[:pending_action] = 'create_pledge'
      session[:pending_pledge] = pledge_attrs
      redirect_to new_user_path
      return
    end

    if !@pledge.save
      render :new
      return
    end

    # Notify the user that their pledge was received.
    flash[:notice] = "Thanks for your pledge! You'll receive an email after the event with a link to process your donation."

    redirect_to @pledge.event
  end

  def is_valid_team?(team_id)
    if team_id && (team = Team.find_by_id(team_id))
      return true
    end

    flash[:alert] = "Please select the event for which you'd like to submit a new pledge."
    redirect_to events_path
    return false
  end

  def pledge_params
    begin
      params.require(:pledge)
        .permit(:team_id,
                :amount,
                :anonymous,
                :monthly,
                :comment)
    rescue ActionController::ParameterMissing => e
      logger.info "Failed to parse pledge params from #{params.inspect}"
      {}
    end
  end
end

app/helpers/pledges_helper.rb
module PledgesHelper
  def donor_name(pledge)
    if pledge.anonymous?
      "Anonymous"
    else
      pledge.donor.full_name
    end
  end
end

app/views/pledges/_form.html.erb
<div class="pledge-form">
  <%= form_for(@pledge) do |f| %>

    <%= f.hidden_field :team_id %>

    <% if @pledge.team.nil? %>
      <div class="field event">
        <div class="label">Event</div>
        <div class="input"><%= link_to @event.title, @event %></div>
      </div>

      <% content_for 'team_id_field' do %>
        <%= f.collection_select :team_id, @event.teams, :id, :name %>
      <% end %>
      <%= render(partial: "shared/form_field",
                 locals: {
                   form: f,
                   model: @pledge,
                   attr: :team_id
                 }) %>
    <% else %>
      <div class="field event">
        <div class="label">Event</div>
        <div class="input"><%= link_to @pledge.event.title, @pledge.event %></div>
      </div>

      <div class="field team">
        <div class="label">Team</div>
        <div class="input"><%= link_to @pledge.team.name, @pledge.team %></div>
      </div>
    <% end %>

    <% content_for 'amount_field' do %>
      <%= f.number_field :amount, placeholder: '$', step: 0.01, min: 0 %>
    <% end %>
    <%= render(partial: "shared/form_field",
               locals: {
                 form: f,
                 model: @pledge,
                 attr: :amount
               }) %>

    <% content_for 'monthly_field' do %>
      <%= f.check_box :monthly %>
    <% end %>
    <%= render(partial: "shared/form_field",
               locals: {
                 form: f,
                 model: @pledge,
                 attr: :monthly
               }) %>

    <div class="actions">
      <%= f.button("Make Pledge", {
                     onClick: '$(".pledge-form form").submit()',
                     type: :submit,
                     class: [:btn, :submit]
                   }) %>
      <%= f.button("Cancel", {
                     onClick: 'window.location.assign("' + cancel_path + '")', 
                     type: :button, 
                     class: [:btn, :cancel]
                   }) %>
    </div>
  <% end %>
</div>

app/views/pledges/_full.json.erb
{
  "pledgeID": <%= pledge.id %>,
  "createdAt": <%= json_string(pledge.created_at) %>,
  "donor": <%= render partial: 'devise/registrations/brief', locals: {user: pledge.donor} %>,
  "anonymous": <%= pledge.anonymous %>,
  "publicDonorName": <%= json_string(donor_name(pledge)) %>,
  "team": <%= render partial: 'teams/brief', locals: {team: pledge.team} %>,
  "amount": <%= pledge.amount %>,
  "monthly": <%= pledge.monthly %>,
  "comment": <%= json_string(pledge.comment) %>
}

app/views/pledges/edit.html.erb
<h1>Editing pledge</h1>

<%= render 'form' %>

<%= link_to 'Show', @pledge %> |
<%= link_to 'Back', pledges_path %>

app/views/pledges/index.html.erb
<h1>Listing pledges</h1>

<table>
  <thead>
    <tr>
      <th>Donor</th>
      <th>Team</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pledges.each do |pledge| %>
      <tr>
        <td><%= pledge.donor %></td>
        <td><%= pledge.team %></td>
        <td><%= pledge.amount %></td>
        <td><%= link_to 'Show', pledge %></td>
        <td><%= link_to 'Edit', edit_pledge_path(pledge) %></td>
        <td><%= link_to 'Destroy', pledge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pledge', new_pledge_path %>

app/views/pledges/new.html.erb
<div id="new-pledge" class="std-form">
  <div class="centerer">
    <div class="instructions">
      <div class="title">Make a Pledge</div>
      <div class="description">Thanks so much for supporting a worthy cause with your pledge. You will receive an email at the completion of the event with a complete summary of the pledges you have made and how you can submit your payment.</div>
    </div>

    <%= render(partial: 'form', locals: {
                 cancel_path: event_path(@pledge.event || @event)
               }) %>
  </div>
</div>