config/routes.rb
Rails.application.routes.draw do

  get 'events/:id/dashboard', to: 'events#dashboard', id: /\d+/, as: 'event_dashboard'
  get 'events/:id/pledge-breakdown', to: 'events#pledge_breakdown', id: /\d+/, as: 'event_pledge_breakdown'
  resources :events do
    resources :pledges, only: [:new]
    resources :teams, only: [:new]
  end
  resources :teams, except: [:index] do
    resources :pledges, only: [:new]
  end
  resources :pledges, only: [:create]
  get 'pledges/process_pending', to: 'pledges#process_pending', as: 'process_pending_pledge'

  resources :users, only: [:new, :create]

  devise_for :users, :controllers => {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }, :skip => [:passwords]

  devise_scope :user do

    get "/users/password/reset/new" => "users/password_resets#new"
    post "/users/password/reset" => "users/password_resets#create"
    get "/users/password/reset/edit" => "users/password_resets#edit"
    put "/users/password/reset" => "users/password_resets#update"
  end

  get 'tour' => 'home#tour'
  get 'about' => 'home#about'

  root 'home#index'

  get ':event_url_key' => 'events#show', as: 'show_event', constraints: ReservedUrlKeyConstraint.new

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_get_started.html.erb
<div class="section get-started">
  <div class="body">
    <div class="hook">
      <div class="intro">Bring some real spirit to your next fundraiser...</div>
      <div>The spirit of competition!</div>
    </div>
    <div class="centerer">
      <%= link_to new_event_path do %>
        <div class="btn">Get Started</div>
      <% end %>
    </div>
    <div class="clear"></div>
  </div>
</div>

app/views/home/_method.html.erb
<div class="section method">
  <div class="body">
    <div class="title">How It Works</div>
    <div class="outline">
      <div class="step plan" data-step="plan">
        <div class="title btn">
          <div class="horiz-line left"></div>
          <div class="text">Plan</div>
          <div class="horiz-line right"></div>
        </div>
        <div class="pic"><%= image_tag "home-plan.jpg" %></div>
      </div>
      <div class="step recruit" data-step="recruit">
        <div class="title btn">
          <div class="horiz-line left"></div>
          <div class="text">Recruit</div>
          <div class="horiz-line right"></div>
        </div>
        <div class="pic"><%= image_tag "home-recruit.jpg" %></div>
      </div>
      <div class="step host" data-step="host">
        <div class="title btn">
          <div class="horiz-line left"></div>
          <div class="text">Host</div>
          <div class="horiz-line right"></div>
        </div>
        <div class="pic"><%= image_tag "home-host.jpg" %></div>
      </div>
      <div class="step follow-up" data-step="follow-up">
        <div class="title btn">
          <div class="horiz-line left"></div>
          <div class="text">Follow Up</div>
          <div class="horiz-line right"></div>
        </div>
        <div class="pic"><%= image_tag "home-followup.jpg" %></div>
      </div>
    </div>
    <div class="steps">
      <div class="step plan">
        <div class="title">Plan the Event</div>
        <div class="description">
          <div class="action">
            <div class="title">Pick an Event Type</div>
            <div class="content">
              Start with a contest or competition that you'd like to structure the event around. This could be a standup comedy show, a battle of the bands, or even a slam-dunk contest. The sky's the limit here, so you can really tailor this to fit the interests of your attendees.
            </div>
          </div>
          <div class="action">
            <div class="title">Set a Goal</div>
            <div class="content">
              Identify your overall donation goal and divide this by the number of teams/participants you plan to include. This will be the goal for each team to raise as part of the event.
            </div>
          </div>
          <div class="action">
            <div class="title">Choose Rewards</div>
            <div class="content">
              Create a reward system for the participants to work toward. This could be a set of donation thresholds, each of which is associated with a different reward, or this could be a set of prizes that are awarded to the top three teams in terms of their cumulative donations received.
            </div>
          </div>
          <div class="action">
            <div class="title">Setup Your Account</div>
            <div class="content">
              At this point you'll create a new fundraiser and event for your organization at TeamRaising.org and populate it with all of this information (e.g. start and end times, prizes, etc). This will give all invitees a single place to go to stay up to date.
            </div>
          </div>
        </div>
      </div>
      <div class="step recruit">
        <div class="title">Recruit Team Captains</div>
        <div class="description">
          <div class="action">
            <div class="title">Get People Involved</div>
            <div class="content">
              Approach a handful of people that are passionate about your organization and/or your cause. Ask them to get involved and head up a team. Depending on the type of event you're planning, these teams may consist of just this single individual or they may need to recruit others to join their team.
            </div>
          </div>
          <div class="action">
            <div class="title">Create the Invitation List</div>
            <div class="content">
              Have each team submit a list of attendees they'd like to have invited to the event. Each team will invite as many family, friends, coworkers, and acquaintances as possible to build a large support base for their team at the event.
            </div>
          </div>
          <div class="action">
            <div class="title">Send Invitations</div>
            <div class="content">
              Feel free to have team captains send invitations directly, as this personal touch to the invitation will likely increase peoples acceptance rate. These attendees are certainly coming to support your cause, but at the same time they're also coming to support their friend or family member. It's a win-win!
            </div>
          </div>
          <div class="action">
            <div class="title">Set Teams on Your Account</div>
            <div class="content">
              Record the set of teams you will have at TeamRaising.org. This will allow us to track the pledges for each team individually and report on the standings in real-time.
            </div>
          </div>
        </div>
      </div>
      <div class="step host">
        <div class="title">Host the Event</div>
        <div class="description">
          <div class="action">
            <div class="title">Sell the Cause</div>
            <div class="content">
              Start the night by selling the attendees on the cause that the event is supporting. Highlight the impact that your organization has. Then, let the games begin.
            </div>
          </div>
          <div class="action">
            <div class="title">Explain the Structure</div>
            <div class="content">
              Walk through the structure of the fundraiser, introduce each of the teams, and talk up the prizes that they'll win for various levels of support.
            </div>
          </div>
          <div class="action">
            <div class="title">Get Them Involved</div>
            <div class="content">
              Point all attendees to the TeamRaising.org mobile site, where they'll be able to check the standings for each team, review the prizes and donation intervals associated with each, and make a pledge to support a particular team.
            </div>
          </div>
          <div class="action">
            <div class="title">Keep Them Up To Date</div>
            <div class="content">
              Load the real-time standings page we provide on a live screen at the event so each team and attendees can track where they stand and encourage people to support them.
            </div>
          </div>
          <div class="action">
            <div class="title">Give Them Options</div>
            <div class="content">
              Depending upon the audience it may also be helpful to sell "funny money" at the door for attendees that would prefer to use cash, as opposed to the online pledges. If you decide to do this, you may also want to have someone walking around with a bucket during each event for people to use this in support of various teams.
            </div>
          </div>
          <div class="action">
            <div class="title">Make Them Excited</div>
            <div class="content">
              Pause at a few points during the event to draw the audiences attention to the standings, celebrate the teams that have a lot of support, and encourage support for teams that are lower in the standings.
            </div>
          </div>
        </div>
      </div>
      <div class="step follow-up">
        <div class="title">Follow up with Your Supporters</div>
        <div class="description">
          <div class="action">
            <div class="title">Convert Pledges into Donations</div>
            <div class="content">
              We will automatically email each registered attendee notifying them of the amount that they pledged and providing a link for them to donate to your organization. Their donation will be made directly to your organization and not through TeamRaising.org.
            </div>
          </div>
          <div class="action">
            <div class="title">Review the Results</div>
            <div class="content">
              In addition to this we will send a report to the event planners outlining the results of the event and the pledges that each team received.
            </div>
          </div>
          <div class="action">
            <div class="title">Celebrate the Success</div>
            <div class="content">
              This will allow you to reach out to the attendees of the event and celebrate the support that they provided. Keeping these individuals engaged and excited about your cause will be an important factor in the success of you future fundraisers.
            </div>
          </div>
          <div class="action">
            <div class="title">Turn Attendees into Supporters</div>
            <div class="content">
              This can make the difference between having a one-time attendee and a lifelong supporter.
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function(){
    setupHomeMethodTransitions();
  });
</script>

app/views/home/_pitch.html.erb
<div class="section pitch">
  <div class="body">
    <div class="vert-centerer"></div>
    <div class="text-container text-carousel">
      <div class="text">
        <div class="vert-align">
          <div class="heading">
            Getting people excited about fundraising
          </div>
          <div class="content">
            By bringing together an interconnected group of friends and making a game out your organization's fundraiser, you'll find that people get more involved and caught up in the excitement of the event.
          </div>
        </div>
      </div>
      <div class="text">
        <div class="vert-align">
          <div class="heading">
            Aligning attendee's interests with your event goals
          </div>
          <div class="content">
            By decomposing your event into a set of teams, you put spread the ownership of the events success across a wider network and allow donors to support your organization's cause while at the same time supporting their friends and family.
          </div>
        </div>
      </div>
      <div class="text">
        <div class="vert-align">
          <div class="heading">
            Putting the FUN back in fundraising
          </div>
          <div class="content">
            Add some friendly competition to your next fundraising event and you'll find it not only helps you reach your fundraising goal but also results in a more exciting and enjoyable experience for your donors.
          </div>
        </div>
      </div>
    </div>
    <div class="img-carousel">
      <div>
        <div class="img-container">
          <div class="vert-align"></div>
          <%= image_tag "home-excitement.png" %>
        </div>
      </div>
      <div>
        <div class="img-container">
          <div class="vert-align"></div>
          <%= image_tag "home-cooperation.png" %>
        </div>
      </div>
      <div>
        <div class="img-container">
          <div class="vert-align"></div>
          <%= image_tag "home-competition.png" %>
        </div>
      </div>
    </div>
    <div class="clear"></div>
  </div>
</div>

<script>
  $(document).ready(function(){
    launchHomeCarousel();
  });
</script>

app/views/home/about.html.erb
<div id="about-us">
  <div class="section service">
    <div class="body">
      <div class="image"><%= image_tag "about/service.png" %></div>
      <div class="content">
        <div class="title">The Service</div>
        <div class="description">
          <p>
            TeamRaising.org is a dynamic fundraising platform designed to support team oriented donation opportunities. Our service allows fundraisers to seamlessly plan and manage fundraising events that bring together a diverse group of interconnected friends and family members to support both the people that they care about and a worthy cause.
          </p>
          <p>
            Structuring a fundraising event around a competition or contest raises the level of interest, excitement, and participation of your attendees. It would be great if people attended fundraising events with the single goal of supporting the featured cause, but that's simply not the case. By centering your event around an engaging activity, you provide attendees with entertainment and additional motivation to support your cause.
          </p>
          <p>
            We're working hard to put the finishing touches on the platform and plan to have it launched shortly. Be sure to check back to see our progress!
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="section vision">
    <div class="body">
      <div class="content">
        <div class="title">The Vision</div>
        <div class="description">
          <p>
            Here at TeamRaising.org we have a dramatic vision for what fundraising events can be in the future: interactive, energetic, competitive, and even fun. We see the great impact that non-profit and donation dependent organizations have on our local, national, and global communities. We see a lot of potential to make fundraisers more enjoyable and effective for both the attendees and hosting organizations. 
          </p>
          <p>
            We are committed to pursuing this vision in whatever direction is found to be most impactful. This will likely include but is not limited to: providing a platform for planning and hosting exciting fundraisers, providing hands on assistance for fundraising planners to ensure the success of these events, taking donations, instead of pledges, at no additional cost to the hosting organization, and exposing a forum for collaboration across host organization's in our community to continue to innovate with fresh ideas and new perspectives.
          </p>
        </div>
      </div>
      <div class="image"><%= image_tag "about/vision.png" %></div>
    </div>
  </div>

  <div class="section team">
    <div class="body">
      <div class="title">The Team</div>
      <div class="member">
        <div class="pic"><%= image_tag "about/hstrowd.jpg" %></div>
        <div class="name">Harrison Strowd</div>
        <div class="bio">
          Harrison has been developing software for over a decade in various corporate, volunteer, and educational environments. He has consistently had a passion for developing applications and services that positively impact the community around him. As the founder of TeamRaising.org, Harrison has been given the opportunity to turn this passion into a groundbreaking platform for a new style of fundraising.
        </div>
        <div class="clear"></div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div id="home">

  <%= render "pitch" %>
  <%= render "method" %>

</div>

app/views/home/tour.html.erb
<div id="tour">
  <div class="section step-1">
    <div class="body">
      <!-- TODO: Allow maximized version of these images to be viewed. -->
      <div class="screenshot">
        <%= link_to(image_tag("tour/1-registerOrg.png", alt: 'Organization Registration Form'),
                    image_path("tour/1-registerOrg.png"),
                    rel: 'step-1-screenshot',
                    class: :fancybox) %>
      </div>
      <div class="text">
        <div class="title">Step 1: Register your Organization</div>
        <div class="description">
          To get started, you'll want to register your organization in the system to capture all the information required to manage your fundraisers. A URL with a custom "URL key" will be generated with the format <span class="org-url">http://teamraising.org/orgs/<span class="custom-key">url-key</span></span>. Sharing this with your team members and donors will allow them to stay up to speed on all your fundraising activities.
        </div>
      </div>
    </div>
  </div>

  <div class="separator"></div>

  <div class="section step-2">
    <div class="body">
      <div class="screenshot">
        <%= link_to(image_tag("tour/2-launchFundraiser.png", alt: 'Fundraiser Planning Form'),
                    image_path("tour/2-launchFundraiser.png"),
                    class: :fancybox) %>
      </div>
      <div class="text">
        <div class="title">Step 2: Plan a Fundraiser</div>
        <div class="description">
          The next step is to setup the fundraiser you'll be running. This will inform everyone of the purpose and other relevant details for the fundraiser, as well as highlighting the window of time during which pledges will be accepted. Fundraisers can span a long period of time and include a number of different events, or they can be quite brief, including only a single event. The choice is totally up to you.
        </div>
      </div>
    </div>
  </div>

  <div class="separator"></div>

  <div class="section step-3">
    <div class="body">
      <div class="screenshot">
        <%= link_to(image_tag("tour/3-scheduleEvent.png", alt: 'Event Scheduling Form'),
                    image_path("tour/3-scheduleEvent.png"),
                    class: :fancybox) %>
      </div>
      <div class="text">
        <div class="title">Step 3: Schedule Events</div>
        <div class="description">
          For each event in the fundraiser, you'll create a separate record to capture the necessary information for your attendees. This is where you can record the date and time for the event, as well as other helpful information like the structure for the event, transportation options, etc.
        </div>
      </div>
    </div>
  </div>

  <div class="separator"></div>

  <div class="section step-4">
    <div class="body">
      <div class="screenshot">
        <%= link_to(image_tag("tour/4-createTeams.png", alt: 'Team Setup Form'),
                    image_path("tour/4-createTeams.png"),
                    class: :fancybox) %>
      </div>
      <div class="text">
        <div class="title">Step 4: Assign Teams</div>
        <div class="description">
          Finally, you'll need to identify the various teams that will be participating in this event. These will be the groups to which donors or attendees submit their pledges. For each team you can set a pledge target, which the system will use to calculate and track their progress.
        </div>
      </div>
    </div>
  </div>

  <div class="separator"></div>

  <div class="section step-5">
    <div class="body">
      <div class="screenshot">
        <%= link_to(image_tag("tour/5-watchDashboard.png", alt: 'Event Dashboard'),
                    image_path("tour/5-watchDashboard.png"),
                    class: :fancybox) %>
      </div>
      <div class="text">
        <div class="title">
          Step 5: Party!!
          <div class="subtitle">(a.k.a. Host the Event)</div>
        </div>
        <div class="description">
          This is where the magic happens! We provide an event dashboard, that graphically highlights the progress of each team in raising pledges during the event. This dashboard automatically updates in realtime as new pledges are submitted. Putting this on display at your event will remind and encourage attendees to support the team of their choosing.
        </div>
      </div>
    </div>
  </div>

  <div class="separator"></div>

  <div class="section step-6">
    <div class="body">
      <div class="screenshot">
        <%= link_to(image_tag("tour/6-followUp.png", alt: 'Pledge Recap Email'),
                    image_path("tour/6-followUp.png"),
                    class: :fancybox) %>
      </div>
      <div class="text">
        <div class="title">Step 6: Follow-Up with Donors</div>
        <div class="description">
          After the event, individuals will need to submit donations directly to your organization in order to fulfill their pledges. To support and remind them of this, we automatically send out a pledge recap email to every individual that submitted a pledge. This email includes a list of all pledges they submitted as well as a link to your donation URL.
        </div>
      </div>
    </div>
  </div>


  <div class="separator"></div>

  <div class="section get-started">
    <div class="intro">
      Ready to make your next fundraiser the talk of the town?
    </div>
    <%= link_to new_event_path do %>
      <div class="btn">Let's Get Started</div>
    <% end %>
  </div>
</div>


<script type="text/javascript">
  var onReady = function() {
    $('.fancybox').fancybox({
      helpers: {
        overlay: {
          locked: false
        }
      }
    });
  };
  $(document).ready(onReady)
</script>