config/routes.rb
Rails.application.routes.draw do

  get 'events/:id/dashboard', to: 'events#dashboard', id: /\d+/, as: 'event_dashboard'
  get 'events/:id/pledge-breakdown', to: 'events#pledge_breakdown', id: /\d+/, as: 'event_pledge_breakdown'
  resources :events do
    resources :pledges, only: [:new]
    resources :teams, only: [:new]
  end
  resources :teams, except: [:index] do
    resources :pledges, only: [:new]
  end
  resources :pledges, only: [:create]
  get 'pledges/process_pending', to: 'pledges#process_pending', as: 'process_pending_pledge'

  resources :users, only: [:new, :create]

  devise_for :users, :controllers => {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }, :skip => [:passwords]

  devise_scope :user do

    get "/users/password/reset/new" => "users/password_resets#new"
    post "/users/password/reset" => "users/password_resets#create"
    get "/users/password/reset/edit" => "users/password_resets#edit"
    put "/users/password/reset" => "users/password_resets#update"
  end

  get 'tour' => 'home#tour'
  get 'about' => 'home#about'

  root 'home#index'

  get ':event_url_key' => 'events#show', as: 'show_event', constraints: ReservedUrlKeyConstraint.new

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :creator, :class_name => 'User'
  belongs_to :team_descriptor

  has_many :teams
  has_many :pledges, :through => :teams do
    def one_time
      where("monthly = FALSE")
    end
    def monthly
      where("monthly = TRUE")
    end
  end

  validates :title, :creator, :start_time, :end_time, :team_descriptor, :presence => true
  validates :title, length: { maximum: 255 }
  validates :url_key, {
    format: { with: /\A[a-zA-Z\-_.~0-9]+\z/, message: "must be URL safe (i.e. alphanumeric or '-', '_', '.', or '~')" },
    # This could alternatively be done using ActionController::Routing::Routes.recognize_path
    exclusion: { in: ApplicationController.reserved_routing_keywords },
    allow_blank: true,
    uniqueness: true,
    length: { maximum: 255 }
  }
  # Capping the description at 5000 characters to prevent malicious entries.
  validates :description, length: { maximum: 5000 }
  validate :start_time_before_end_time

  validates_with UrlValidator, fields: [:logo_url]

  def has_started?
    self.start_time < DateTime.now
  end

  def has_ended?
    self.end_time < DateTime.now
  end

  def is_active?
    has_started? && !has_ended?
  end

  def is_member?(user)
    user && user.is_admin?
  end

  def pledge_target
    self.teams.sum(:pledge_target)
  end

  def pledge_total
    self.pledges.one_time.sum(:amount) +
      (self.pledges.monthly.sum(:amount) * 12)
  end

private

  def start_time_before_end_time
    if start_time && end_time && (start_time > end_time)
      errors.add(:start_time, "can't be after the end time")
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include DateHelper

  respond_to :html, :json
  layout "raw", only: [:dashboard]

  before_action :authenticate_user!, except: [:show]
  before_action :require_admin!, only: [:new, :create, :edit, :update]
  before_action :lookup_event, except: [:index, :new, :create]

  def index
    @events = Event.where("start_time <= ? AND end_time >= ?",
                          (DateTime.now + 3.hours),
                          (DateTime.now - 3.hours))
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.creator = current_user

    if !@event.save
      render :new
      return
    end

    redirect_to @event
    return
  end

  def update
    if !@event.update_attributes(event_params)
      render :edit
      return
    end

    redirect_to @event
    return
  end

  def dashboard
  end

  def pledge_breakdown
    pledge_breakdown = @event.teams.order(:name).inject([]) do |donations, team|
      data_label = "#{team.name} (#{team.pledges.count})"
      donations << [data_label, team.pledge_total]
      donations
    end

    respond_with(pledge_breakdown)
  end

private

  def lookup_event
    @event = Event.find_by_id(params[:id]) if params[:id]

    # Check if the url_keys were specified for this request.
    if !@event && params[:event_url_key]
      @event = Event.find_by_url_key(params[:event_url_key])
    end

    if !@event
      respond_to do |format|
        format.html {
          flash[:alert] = 'Unable to find requested event.'
          if current_user
            redirect_to events_path
          else
            redirect_to root_path
          end
        }
        format.json { render :json => {:error => 'Event not found.'}.to_json, :status => 404 }
      end
    end
  end

  def event_params
    input_params = {}
    begin
      input_params = params.require(:event)
        .permit(:title,
                :description,
                :url_key,
                :start_time,
                :end_time,
                :logo_url,
                :team_descriptor_id)
    rescue ActionController::ParameterMissing => e
      logger.info "Failed to parse event params from #{params.inspect}"
    end

    # Parse date values.
    if input_params.has_key?(:start_time)
      input_params[:start_time] = parseIso8601Date(input_params[:start_time])
    end
    if input_params.has_key?(:end_time)
      input_params[:end_time] = parseIso8601Date(input_params[:end_time])
    end

    input_params
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def pledge_progress_percent(event)
    if (event.pledge_target == 0)
      0
    else
      (event.pledge_total / event.pledge_target * 100).round
    end
  end

  def show_url(event)
    return new_event_pledge_url(event, protocol: secure_protocol)
  end

  def thirty_minute_internvals
    [ '12:00 am',
      '12:30 am',
      '1:00 am',
      '1:30 am',
      '2:00 am',
      '2:30 am',
      '3:00 am',
      '3:30 am',
      '4:00 am',
      '4:30 am',
      '5:00 am',
      '5:30 am',
      '6:00 am',
      '6:30 am',
      '7:00 am',
      '7:30 am',
      '8:00 am',
      '8:30 am',
      '9:00 am',
      '9:30 am',
      '10:00 am',
      '10:30 am',
      '11:00 am',
      '11:30 am',
      '12:00 pm',
      '12:30 pm',
      '1:00 pm',
      '1:30 pm',
      '2:00 pm',
      '2:30 pm',
      '3:00 pm',
      '3:30 pm',
      '4:00 pm',
      '4:30 pm',
      '5:00 pm',
      '5:30 pm',
      '6:00 pm',
      '6:30 pm',
      '7:00 pm',
      '7:30 pm',
      '8:00 pm',
      '8:30 pm',
      '9:00 pm',
      '9:30 pm',
      '10:00 pm',
      '10:30 pm',
      '11:00 pm',
      '11:30 pm']
  end
end

app/views/events/_form.html.erb
<div class="event-form">
  <%= form_for @event do |f| %>

    <%= render(partial: "shared/form_field", 
               locals: { 
                 form: f, 
                 model: @event, 
                 attr: :title,
                 field_label: 'Event Title'
               }) %>

    <% content_for 'description_field' do %>
      <%= f.text_area :description %>
    <% end %>
    <%= render(partial: "shared/form_field", 
               locals: { 
                 form: f, 
                 model: @event, 
                 attr: :description
               }) %>

    <%= render(partial: "shared/form_field",
               locals: {
                 form: f,
                 model: @event,
                 field_label: :unique_key,
                 attr: :url_key,
                 info: "Used in URLs (e.g. https://teamraising.org/<div class=\"variable\">unique-key</div>/)."
               }) %>

    <% content_for 'team_descriptor_field' do %>
      <%= f.collection_select :team_descriptor_id, TeamDescriptor.all, :id, :plural %>
    <% end %>
    <%= render(partial: "shared/form_field",
               locals: {
                 form: f,
                 model: @event,
                 attr: :team_descriptor,
                 field_label: 'Type of Teams',
                 info: "If you don't see the descriptor you would like to use, please email #{mail_to "support@teamraising.org"}."
               }) %>

    <% content_for 'start_time_field' do %>
      <%= f.hidden_field(:start_time, value: @event.start_time) %>
      <% if !@event.errors[:start_time].empty? %>
        <div class="field_with_errors">
      <% end %>
      <%= text_field_tag :date_start, nil, class: 'datetime date' %>
      <div class="datetime-separator">at</div>
      <%= text_field_tag :time_start, nil, class: 'datetime time' %>
      <% if !@event.errors[:start_time].empty? %>
        </div>
      <% end %>
    <% end %>
    <%= render(partial: "shared/form_field", 
               locals: { 
                 form: f, 
                 model: @event, 
                 field_label: 'Starts on',
                 attr: :start_time
               }) %>

    <% content_for 'end_time_field' do %>
      <%= f.hidden_field(:end_time, value: @event.end_time) %>
       <% if !@event.errors[:end_time].empty? %>
         <div class="field_with_errors">
       <% end %>
       <%= text_field_tag :date_end, nil, class: 'datetime date' %>
       <div class="datetime-separator">at</div>
       <%= text_field_tag :time_end, nil, class: 'datetime time' %>
       <% if !@event.errors[:end_time].empty? %>
         </div>
       <% end %>
    <% end %>
    <%= render(partial: "shared/form_field", 
               locals: { 
                 form: f, 
                 model: @event,
                 field_label: 'Ends on',
                 attr: :end_time
               }) %>
    <%= render(partial: "shared/form_field",
               locals: {
                 form: f,
                 model: @event,
                 attr: :logo_url,
                 info: 'Used as an icon for all your records. We suggest for this image to be approximately 128 x 128 pixels.'
               }) %>

    <div class="actions">
      <%= f.button(action + " Event", {
                     onClick: '$(".event-form form").submit()', 
                     type: :submit,
                     class: [:btn, :submit]
                   }) %>
      <%= f.button("Cancel", {
                     onClick: 'window.location.assign("' + cancel_path + '")',
                     type: :button,
                     class: [:btn, :cancel]
                   }) %>
    </div>

    <script>
      $(function() {
        initDateTimeField('event', 'start');
        initDateTimeField('event', 'end');

        // Ensure the end date/time is always after the start date/time.
        maintainChronologicalOrder('event', 'start', 'end');
      });
    </script>

  <% end %>
</div>

app/views/events/_full.json.erb
{
  "eventID": <%= event.id %>,
  "title": <%= json_string(event.title) %>,
  "startTime": <%= json_string(event.start_time) %>,
  "endTime": <%= json_string(event.end_time) %>,
  "pledges": [
    <% event.pledges.order(created_at: :desc).limit(15).each_with_index do |pledge, index| %>
      <%= (index != 0) ? ',' : '' %>
      <%= render partial: 'pledges/full', locals: {pledge: pledge} %>
    <% end %>
  ],
  "pledgeTarget": <%= event.pledge_target %>,
  "pledgeTotal": <%= event.pledge_total %>
}

app/views/events/_list_item.html.erb
<div class="item event">
  <div class="header">
    <% if show_full_context %>
      <div class="icon">
        <% if !event.logo_url.blank? %>
          <%= image_tag event.logo_url, alt: 'Event Logo' %>
        <% end %>
      </div>
    <% end %>

    <div class="title">
      <%= link_to event.title, event %>
    </div>
    <div class="assoc-count">
      (<%= pluralize(event.teams.count, 'team') %>)
    </div>
  </div>
  <div class="description">
      <%= render partial: 'shared/toggleable_size',
          locals: { less_height: 60, content: event.description } %>
  </div>

  <% if event.has_ended? %>
    <div class="attr date ended">
      <div class="label">Ended At:</div>
      <div class="value"><%= event.end_time %></div>
    </div>
  <% elsif event.has_started? %>
    <div class="attr date ending">
      <div class="label">Ending At:</div>
      <div class="value"><%= event.end_time %></div>
    </div>
  <% else %>
    <div class="attr date starting">
      <div class="label">Starts At:</div>
      <div class="value"><%= event.start_time %></div>
    </div>
  <% end %>

  <% if event.has_started? %>
    <div class="attr pledges">
      <div class="label">Progress:</div>
      <div class="value">
        <div class="percent">
          <% if (event.pledge_target > 0) %>
            <%= (event.pledge_total / event.pledge_target * 100).round() %>%
          <% else %>
            0%
          <% end %>
        </div>
        (<div class="total">$<%= event.pledge_total.round() %></div>
        <div class="count">from <%= pluralize(event.pledges.count, 'pledge') %></div>)
      </div>
    </div>
  <% else %>
    <div class="attr pledge-target">
      <div class="label">Pledge Target:</div>
      <div class="value">$<%= event.pledge_target.round() %></div>
    </div>
  <% end %>

</div>

<script>
  $(function() { convertToLocalTime('.item.event .attr.date .value').show(); });
</script>

app/views/events/dashboard.html.erb
<%= javascript_include_tag "//code.highcharts.com/highcharts.js", "chartkick" %>

<div id="event-dashboard">
  <div class="pad"></div>

  <div class="header">
    <div class="vert-centerer"></div>
    <div class="logo">
      <% if !@event.logo_url.blank? %>
        <%= link_to show_event_path(@event) do %>
          <%= image_tag @event.logo_url %>
        <% end %>
      <% end %>
    </div>
    <div class="text">
      <div class="title">
        <%= @event.title %>
      </div>
    </div>
    <% if !@event.has_started? %>
      <div class="clock start">
        <div class="vert-centerer"></div>
        <div class="text">Starts in <span id="start-countdown" class="countdown"></span></div>
      </div>
    <% elsif @event.is_active? %>
      <div class="clock end">
        <div class="vert-centerer"></div>
        <div class="text">Ends in <span id="end-countdown" class="countdown"></span></div>
      </div>
    <% else %>
      <div class="clock done">
        <div class="vert-centerer"></div>
        <div class="text">Finished!</div>
      </div>
    <% end %>
  </div>

  <div class="pad"></div>

  <div class="event-details">
    <div class="tabs">
      <div class="tab tab-0 panel selected" data-tab="pledge-breakdown" data-index="0">
        <div class="vert-centerer"></div>
        Totals per <%= @event.team_descriptor.singular %>
      </div>
      <div class="tab tab-1 panel" data-tab="pledge-log" data-index="1">
        <div class="vert-centerer"></div>
        Pledge Log
      </div>
      <div class="tab button" onClick="toggleAutoRotate($('#event-dashboard .event-details'));">
        <div class="pad"></div>
        <%= image_tag 'events/dashboard/auto-rotate.png' %>
      </div>
    </div>

    <div class="pledge-breakdown tab-container tab-0 selected">
      <div class="pad"></div>
      <div class="tab-body">
        <div class="title">
          <div class="vert-centerer"></div>
          Pledge Totals per <%= @event.team_descriptor.singular %>
        </div>
        <div id="chart-pledge-breakdown">Loading...</div>

        <div class="pad"></div>

        <div class="overall">
          <div class="title">
            <div class="vert-centerer"></div>
            Overall Progress
          </div>
          <div class="progress-bar">
            <div class="pct-complete">
              <div class="label-align">
                <div class="vert-centerer"></div>
                <div class="label"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="pad"></div>
    </div>

    <div class="pledge-log tab-container tab-1">
      <div class="pad"></div>
      <div class="tab-body">
        <div class="title">Recent Pledges</div>
        <div class="headers">
          <div class="vert-centerer"></div>
          <div class="column donor">Donor</div>
          <div class="column team"><%= @event.team_descriptor.singular %></div>
          <div class="column comment">Comment</div>
        </div>
        <div class="list">
          <!-- Pledge records get added here dynamically. -->
        </div>
      </div>
      <div class="pad"></div>
    </div>

  </div>

  <div class="pad"></div>

  <div class="pledge-prompt">
    <div class="vert-centerer"></div>
    <span class="url"><%= link_to show_url(@event), show_url(@event) %></span>
  </div>
</div>

<script id="pledge-item" type="x-tmpl-mustache">
  <div class="pledge" data-pledge-id="{{ pledgeID }}">
    <div class="attr donor">{{ publicDonorName }}</div>
    <div class="attr team">{{ team.name }}</div>
    <div class="attr comment">{{ comment }}</div>
  </div>
</script>
<script>
  $(document).ready(function() {
    var template = $('#pledge-item').html();
    Mustache.parse(template);   // speeds up future uses

    setupCountdown('#start-countdown', '<%= @event.start_time.iso8601() %>');
    setupCountdown('#end-countdown', '<%= @event.end_time.iso8601() %>');

    setupAutoRefresh(<%= @event.id %>);
    var $eventDetails = $("#event-dashboard .event-details");
    setupTabs($eventDetails);
    $eventDetails.on('tabChange', function(e, newTab) {
      if (newTab == 'pledge-log') {
        resetAutoScroll($eventDetails.find('.pledge-log .tab-body .list'));
      }
    });
  });
</script>

app/views/events/edit.html.erb
<div id="event-edit" class="std-form">
  <div class="centerer">
    <div class="instructions">
      <div class="title">Update Event</div>
      <div class="description">
        Use the form below to update the details for your event.
      </div>
    </div>

    <%= render(partial: 'form', locals: {
                 action: 'Update',
                 cancel_path: event_path(@event)
               }) %>

  </div>
</div>

app/views/events/index.html.erb
<div id="event-index">
  <div class="centerer">
    <div class="intro">
      <div class="title">Active Events</div>
      <div class="description">Check out the following events that are scheduled to start soon, are currently taking place, or ended recently.</div>
    </div>

    <% if (@events.count > 0) %>
      <div class="list">
        <% @events.each do |event| %>
          <%= render partial: 'list_item', locals: { event: event, show_full_context: true } %>
        <% end %>
      </div>
    <% else %>
      <div class="list empty">
        No events found.
      </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div id="new-event" class="std-form">
  <div class="centerer">
    <div class="instructions">
      <div class="title">Schedule an Event</div>
      <div class="description">
        What an exciting time it will be! Fill in the details for the event you'll be hosting. Be sure to include all the details people will want to know, such as the theme/entertainment, location, attire, etc.
      </div>
    </div>

    <%= render(partial: 'form', locals: {
                 action: 'Schedule',
                 cancel_path: events_path
               }) %>
  </div>
</div>

app/views/events/show.html.erb
<div id="event-show">

  <div class="header">
    <div class="icon">
      <% if !@event.logo_url.blank? %>
        <%= image_tag @event.logo_url, alt: 'Event Logo' %>
      <% end %>
    </div>
    <div class="text">
      <div class="title">
        <%= @event.title %>
      </div>
    </div>
  </div>

  <div class="controls">
    <% if @event.is_member?(current_user) %>
      <% if !@event.has_ended? %>
        <%= link_to new_event_team_path(@event) do %>
          <div class="action btn new-team">Add a <%= @event.team_descriptor.singular %></div>
        <% end %>
      <% end %>
      <%= link_to edit_event_path(@event) do %>
        <div class="action btn edit-event">Update Event</div>
      <% end %>
      <% if @event.is_active? %>
        <%= link_to event_dashboard_path(@event), data: { 'no-turbolink' => true } do %>
          <div class="action btn launch-dashboard">Launch Dashboard</div>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div class="association teams">
    <% if !@event.teams.empty? %>
      <div class="list">
        <% @event.teams.each do |t| %>
          <%= render partial: 'teams/list_item', locals: { team: t } %>
        <% end %>
      </div>
    <% else %>
      <div class="notice">No teams registered yet!</div>
    <% end %>
  </div>

</div>

<script>
  $(function() {
    convertToLocalTime('#event-show .time .start.time');
    convertToLocalTime('#event-show .time .end.time');
    $('#event-show .time .timeframe').show();
  });
</script>

app/views/events/show.json.erb
<%= render partial: 'full', locals: {event: @event} %>