config/routes.rb
Rails.application.routes.draw do

  get 'events/:id/dashboard', to: 'events#dashboard', id: /\d+/, as: 'event_dashboard'
  get 'events/:id/pledge-breakdown', to: 'events#pledge_breakdown', id: /\d+/, as: 'event_pledge_breakdown'
  resources :events do
    resources :pledges, only: [:new]
    resources :teams, only: [:new]
  end
  resources :teams, except: [:index] do
    resources :pledges, only: [:new]
  end
  resources :pledges, only: [:create]
  get 'pledges/process_pending', to: 'pledges#process_pending', as: 'process_pending_pledge'

  resources :users, only: [:new, :create]

  devise_for :users, :controllers => {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }, :skip => [:passwords]

  devise_scope :user do

    get "/users/password/reset/new" => "users/password_resets#new"
    post "/users/password/reset" => "users/password_resets#create"
    get "/users/password/reset/edit" => "users/password_resets#edit"
    put "/users/password/reset" => "users/password_resets#update"
  end

  get 'tour' => 'home#tour'
  get 'about' => 'home#about'

  root 'home#index'

  get ':event_url_key' => 'events#show', as: 'show_event', constraints: ReservedUrlKeyConstraint.new

end

app/views/layouts/_account_management.html.erb
<div class="nav-items">
  <% if current_user %>

    <%= link_to events_path do %>
      <div class="nav-item">Find an Event</div>
    <% end %>
    <%= link_to edit_user_registration_url(current_user.id, protocol: secure_protocol) do %>
      <div class="nav-item">Account Info</div>
    <% end %>
    <%= link_to destroy_session_path(:user), method: :delete do %>
      <div class="nav-item">Log Out</div>
    <% end %>

  <% else %>

    <%= link_to new_session_url(:user, protocol: secure_protocol, redirect: request.fullpath) do %>
      <div class="nav-item">Log In</div>
    <% end %>

    <%= link_to new_registration_url(:user, protocol: secure_protocol, redirect: request.fullpath) do %>
      <div class="nav-item">Sign Up</div>
    <% end %>

  <% end %>
</div>

app/views/layouts/_base_structure.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamRaising.org - A platform for team-based fundraising.</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>

    <meta name="description" content="A team-based fundraising platform that generates more interest and excitement for fundraisers by providing a realtime dashboard of pledge activity.">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= yield(:head) %>
  </head>
  <body>

    <div id="page-container">
      <% if content_for?('header') %>
        <%= yield('header') %>
      <% end %>

      <%= yield('page_content') %>

      <div id="footer">
        <div class="centerer">
          <div class="copyright">Copyright &copy; 2014 - 2015, TeamRaising.org | All rights reserved.</div>
          <div class="links">
            <%= link_to 'Privacy Policy', privacy_url %> | <a href="http://www.strowd.com">strowd.com</a>
          </div>
        </div>
      </div>
    </div>

    <script>
      $(function() {
        var toggleableSizeFields = $('.toggle-size');
        setupSizeToggling(toggleableSizeFields);

        checkForSizeToggling(toggleableSizeFields);
        window.onresize = function(event) {
          checkForSizeToggling(toggleableSizeFields);
        };
      });
    </script>
  </body>
</html>

app/views/layouts/_login_form.html.erb
<div class="login">
  <div class="align-helper">
    <%= form_tag session_url(:user, protocol: secure_protocol) do |f| %>
      <div class="field">
        <div class="label">
          <%= label_tag :email %>
        </div>
        <%= email_field_tag 'user[email]', '', autofocus: true %>
      </div>

      <div class="field">
        <div class="label">
          <%= label_tag :password %>
        </div>
        <%= password_field_tag 'user[password]', '', autocomplete: "off" %>
      </div>

      <div class="field">
        <%= check_box_tag 'user[remember_me]' %>
        <div class="label">
          <%= label_tag :remember_me %>
        </div>
      </div>

      <%= hidden_field_tag 'redirect', request.fullpath %>

      <div class="actions">
        <%= button_tag "Submit", {
              onClick: '$(".login form").submit()',
              type: :submit,
              class: [:btn, :submit]
            } %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_primary_navigation.html.erb
<div class="nav-items">
  <%= link_to root_path do %>
    <div class="nav-item home">
      <div class="vert-centerer"></div>Home
    </div>
  <% end %>
  <%= link_to(tour_path, data: { 'no-turbolink' => true }) do %>
    <div class="nav-item org-index">
      <div class="vert-centerer"></div>Take a Tour
    </div>
  <% end %>
  <%= link_to(new_event_url(protocol: secure_protocol)) do %>
    <div class="nav-item event-new">
      <div class="vert-centerer"></div>Start Raising
    </div>
  <% end %>
  <%= link_to about_path do %>
    <div class="nav-item about">
      <div class="vert-centerer"></div>About Us
    </div>
  <% end %>
</div>

app/views/layouts/_user_nav.html.erb
<div id="user-nav">
  <%= link_to 'My Organizations', organizations_path %>
  <%= link_to 'Log Out', destroy_session_path(:user), class: 'logout-btn', method: :delete %>
</div>

app/views/layouts/application.html.erb
<% content_for 'header' do %>
  <div id="header">

    <div class="centerer">
      <div class="vert-centerer"></div>
      <div class="main-logo">
        <div class="vert-centerer"></div>
        <%= image_tag 'logo-small.png' %>
      </div>

      <div class="menu primary-nav">
        <div class="menu-btn">
          <div class="vert-centerer"></div>
          <%= image_tag "menu.png" %>
        </div>
        <!-- An empty div ensures the dropdown menu always appears below its respective button. -->
        <div></div>
        <div class="menu-dropdown">
          <div class="vert-centerer"></div>
          <%= render "layouts/primary_navigation" %>
        </div>
      </div>

    </div>

    <!-- The login form should span the width of the page. -->
    <%= render "layouts/login_form" %>

  </div>
  <div id="header-stub"></div>
<% end %>


<% content_for 'page_content' do %>
  <div id="page-content">
    <div id="notifications">
      <div class="notice">
        <% if notice %>
          <div class="centerer"><%= notice %></div>
        <% end %>
        <!-- Add JS to close the notification after a few seconds. -->
      </div>
      <div class="alert">
        <% if alert %>
          <div class="centerer"><%= alert %></div>
        <% end %>
      </div>
    </div>

    <%= yield %>
  </div>
<% end %>


<%= render "layouts/base_structure" %>

app/views/layouts/raw.html.erb
<% content_for 'header' do %>
<% end %>

<% content_for 'page_content' do %>
  <div id="page-content" class="dashboard">
    <%= yield %>
  </div>
<% end %>


<%= render "layouts/base_structure" %>